In [1]:
import numpy as np
import pandas as pd

importing production data

In [59]:
production = pd.read_csv('/content/Recruitment Task 2026-27 - Production (1).csv',skiprows=3)
production = production.drop('Unnamed: 5',axis =1).dropna()

importing retail sales data

In [60]:
retail = pd.read_csv('/content/Recruitment Task 2026-27 - Retail Sales.csv',skiprows=3)
retail = retail.drop('Unnamed: 6',axis=1).dropna()

importing stall sales data

In [61]:
stall_sales = pd.read_csv('/content/Recruitment Task 2026-27 - Stall Sales.csv',skiprows=3)
stall_sales = stall_sales.drop('Unnamed: 5',axis = 1).dropna()

In [48]:
production.info()
production.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   S.No                           55 non-null     int64
 1   Date                           55 non-null     object
 2   Category                       55 non-null     object
 3   Total Products                 55 non-null     int64
 4   Defective Products             55 non-null     int64
 5   Unnamed: 5                     0 non-null      float64
 6   Cost of Production (per unit)  55 non-null     int64
 7   Wages (per unit)               55 non-null     int64
 8   Raw Material Batch ID          55 non-null     object
 9   Artisan Name/ID                55 non-null     object
dtypes: float64(1), int64(5), object(4)
memory usage: 4.4+ KB

S.No                              0
Date                              0
Category                          0
Total Products                    0
Defective Products                0
Unnamed: 5                       55
Cost of Production (per unit)     0
Wages (per unit)                  0
Raw Material Batch ID             0
Artisan Name/ID                   0
dtype: int64

In [62]:
retail.info()
retail.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
Index: 24 entries, 0 to 23
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   S.No              24 non-null     object
 1   Order ID          24 non-null     object
 2   Date              24 non-null     object
 3   Category          24 non-null     object
 4   Price             24 non-null     float64
 5   Quantity          24 non-null     float64
 6   Total Amount      24 non-null     float64
 7   Shipping Charges  24 non-null     float64
 8   Return Status     24 non-null     object
dtypes: float64(4), object(5)
memory usage: 1.9+ KB

S.No                0
Order ID            0
Date                0
Category            0
Price               0
Quantity            0
Total Amount        0
Shipping Charges    0
Return Status       0
dtype: int64

In [63]:
stall_sales.info()
stall_sales.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
Index: 14 entries, 0 to 24
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   S.No            14 non-null     int64
 1   Date            14 non-null     object
 2   Category        14 non-null     object
 3   Price           14 non-null     int64
 4   Quantity        14 non-null     int64
 5   Total Amount    14 non-null     int64
 6   Discount (%)    14 non-null     int64
 7   Payment Method  14 non-null     object
dtypes: int64(5), object(3)
memory usage: 1008.0+ bytes

S.No              0
Date              0
Category          0
Price             0
Quantity          0
Total Amount      0
Discount (%)      0
Payment Method    0
dtype: int64

In [64]:
operations = pd.read_csv('/content/Recruitment Task 2026-27 - Operational Expenses.csv',skiprows=3)
operations

,Expense ID,Date,Expense Category,Expenese Channel,Description,Amount
0,E01,06-Oct-2025,Stall Operations,Stall,KMC Campus Stall Rental (Oct),1000
1,E02,15-Oct-2025,Logistics,Retail,Transport for raw materials,450
2,E03,25-Oct-2025,Packaging,Retail,Bulk order of packaging bags,600
3,E04,29-Oct-2025,Utilities,Stall,Artisan workshop electricity bill,800
4,E05,01-Nov-2025,Marketing,Retail,Social Media Ad Boost (Fest),750
5,E06,08-Nov-2025,Stall Operations,Stall,Diwali Fest Stall Rental (Nov),2000
6,E07,18-Nov-2025,Logistics,Retail,Transport for finished goods,550
7,E08,26-Nov-2025,Packaging,Retail,Order of premium packaging boxes,850
8,E09,30-Nov-2025,Utilities,Stall,Artisan workshop electricity bill,950

In [65]:
production.head()

,S.No,Date,Category,Total Products,Defective Products,Cost of Production (per unit),Wages (per unit),Raw Material Batch ID,Artisan Name/ID
0,1,01-Oct-2025,Cotton Scarf,15,1,85,40,RM-A-101,A01
1,2,02-Oct-2025,T-Shirt,10,0,180,60,RM-A-101,A02
2,3,03-Oct-2025,Chanderi Dupatta,8,0,210,55,RM-A-102,A03
3,4,04-Oct-2025,Chanderi Scarf,12,0,150,50,RM-A-102,A04
4,5,05-Oct-2025,cotton scarf,15,0,87,40,RM-B-103,A01

In [66]:
retail.head()

,S.No,Order ID,Date,Category,Price,Quantity,Total Amount,Shipping Charges,Return Status
0,1,EN-1001,05-Oct-2025,T-Shirt,450.0,1.0,450.0,60.0,Kept
1,2,EN-1002,06-Oct-2025,Cotton Scarf,250.0,2.0,500.0,60.0,Kept
2,3,EN-1003,09-Oct-2025,Chanderi Scarf,400.0,1.0,400.0,60.0,Kept
3,4,EN-1004,11-Oct-2025,Chanderi Dupatta,550.0,1.0,550.0,70.0,Kept
4,5,EN-1005,13-Oct-2025,T-Shirt,450.0,1.0,450.0,60.0,Returned

In [67]:
stall_sales.head()

,S.No,Date,Category,Price,Quantity,Total Amount,Discount (%),Payment Method
0,1,07-Oct-2025,Cotton Scarf,300,2,600,0,Cash
2,3,08-Oct-2025,Chanderi Scarf,480,2,960,0,Card
4,5,14-Oct-2025,cotton scarf,300,3,900,5,UPI
6,7,15-Oct-2025,Chanderi Scarf,480,1,480,0,UPI
7,8,21-Oct-2025,Cotton Scarf,300,4,1200,5,Cash

production summary

In [75]:
production['Date'] = pd.to_datetime(
    production['Date'],
    dayfirst=True
)
production['Month'] = production['Date'].dt.month_name()
production[['Date', 'Month']].head()

        Date    Month
0 2025-10-01  October
1 2025-10-02  October
2 2025-10-03  October
3 2025-10-04  October
4 2025-10-05  October

In [78]:
production_summary = production.groupby(
    ['Month', 'Category']
).agg(
    Total_Produced=('Total Products', 'sum'),
    Total_Defective=('Defective Products', 'sum')
).reset_index()
production_summary

       Month          Category  Total_Produced  Total_Defective
0   November  Chanderi Dupatta              86                0
1   November    Chanderi Scarf              88                1
2   November      Cotton Scarf             137                4
3   November           T-Shirt             126                4
4   November  chanderi Dupatta              15                0
5   November    chanderi scarf              38                0
6   November      cotton scarf              22                1
7    October  Chanderi Dupatta              52                2
8    October    Chanderi Scarf              63                0
9    October      Cotton Scarf              90                5
10   October           T-Shirt              82                2
11   October    chanderi scarf              15                0
12   October      cotton scarf              30                1

In [80]:
## calculating the good products
production_summary['Good_Products'] = (
    production_summary['Total_Produced']
    - production_summary['Total_Defective']
)
## calculating the defect rate
production_summary['Defect_Rate_%'] = (
    production_summary['Total_Defective']
    / production_summary['Total_Produced']
) * 100
production_summary

,Month,Category,Total_Produced,Total_Defective,Good_Products,Defect_Rate_%
0,November,Chanderi Dupatta,86,0,86,0.000000
1,November,Chanderi Scarf,88,1,87,1.136364
2,November,Cotton Scarf,137,4,133,2.919708
3,November,T-Shirt,126,4,122,3.174603
4,November,chanderi Dupatta,15,0,15,0.000000
5,November,chanderi scarf,38,0,38,0.000000
6,November,cotton scarf,22,1,21,4.545455
7,October,Chanderi Dupatta,52,2,50,3.846154
8,October,Chanderi Scarf,63,0,63,0.000000
9,October,Cotton Scarf,90,5,85,5.555556
10,October,T-Shirt,82,2,80,2.439024
11,October,chanderi scarf,15,0,15,0.000000
12,October,cotton scarf,30,1,29,3.333333

In [90]:
retail['Date'] = pd.to_datetime(
    retail['Date'],
    dayfirst=True
)
retail['Month'] = retail['Date'].dt.month_name()
retail['Category'] = retail['Category'].str.strip().str.title()
retail['Return Status'].value_counts()

Return Status
Kept        21
Returned     3
Name: count, dtype: int64

In [100]:
retail['Net Sales Amount'] = retail['Total Amount'].where(
    retail['Return Status'] == 'Kept',
    0
)
retail['Net Quantity Sold'] = retail['Quantity'].where(
    retail['Return Status'] == 'Kept',
    0
)
retail['Returned Quantity'] = retail['Quantity'].where(
    retail['Return Status'] == 'Returned',
    0
)
retail.head()

,S.No,Order ID,Date,Category,Price,Quantity,Total Amount,Shipping Charges,Return Status,Month,Net Sales Amount,Net Quantity Sold,Returned Quantity
0,1,EN-1001,2025-10-05,T-Shirt,450.0,1.0,450.0,60.0,Kept,October,450.0,1.0,0.0
1,2,EN-1002,2025-10-06,Cotton Scarf,250.0,2.0,500.0,60.0,Kept,October,500.0,2.0,0.0
2,3,EN-1003,2025-10-09,Chanderi Scarf,400.0,1.0,400.0,60.0,Kept,October,400.0,1.0,0.0
3,4,EN-1004,2025-10-11,Chanderi Dupatta,550.0,1.0,550.0,70.0,Kept,October,550.0,1.0,0.0
4,5,EN-1005,2025-10-13,T-Shirt,450.0,1.0,450.0,60.0,Returned,October,0.0,0.0,1.0

In [102]:
retail_summary = retail.groupby(
    ['Month', 'Category']
).agg(
    Units_Sold=('Net Quantity Sold', 'sum'),
    Returned_Units=('Returned Quantity', 'sum'),
    Gross_Revenue=('Total Amount', 'sum'),
    Net_Revenue=('Net Sales Amount', 'sum')
).reset_index()
retail_summary

,Month,Category,Units_Sold,Returned_Units,Gross_Revenue,Net_Revenue
0,November,Chanderi Dupatta,3.0,0.0,1650.0,1650.0
1,November,Chanderi Scarf,4.0,0.0,1600.0,1600.0
2,November,Cotton Scarf,11.0,0.0,2750.0,2750.0
3,November,T-Shirt,2.0,3.0,2250.0,900.0
4,October,Chanderi Dupatta,2.0,0.0,1100.0,1100.0
5,October,Chanderi Scarf,2.0,0.0,800.0,800.0
6,October,Cotton Scarf,6.0,0.0,1500.0,1500.0
7,October,T-Shirt,4.0,1.0,2250.0,1800.0

stall sales

In [108]:
stall_sales['Date'] = pd.to_datetime(
    stall_sales['Date'],
    dayfirst=True
)

stall_sales['Month'] = stall_sales['Date'].dt.month_name()
stall_sales['Category'] = (
    stall_sales['Category']
    .str.strip()
    .str.title()
)
stall_sales['Net Revenue'] = (
    stall_sales['Total Amount'] *
    (1 - stall_sales['Discount (%)'] / 100)
)
stall_sales.head()

,S.No,Date,Category,Price,Quantity,Total Amount,Discount (%),Payment Method,Month,Net Revenue
0,1,2025-10-07,Cotton Scarf,300,2,600,0,Cash,October,600.0
2,3,2025-10-08,Chanderi Scarf,480,2,960,0,Card,October,960.0
4,5,2025-10-14,Cotton Scarf,300,3,900,5,UPI,October,855.0
6,7,2025-10-15,Chanderi Scarf,480,1,480,0,UPI,October,480.0
7,8,2025-10-21,Cotton Scarf,300,4,1200,5,Cash,October,1140.0

In [110]:
stall_summary = stall_sales.groupby(
    ['Month', 'Category']
).agg(
    Units_Sold=('Quantity', 'sum'),
    Gross_Revenue=('Total Amount', 'sum'),
    Net_Revenue=('Net Revenue', 'sum')
).reset_index()
stall_summary
stall_sales[['Total Amount', 'Discount (%)', 'Quantity']].head(10)

    Total Amount  Discount (%)  Quantity
0            600             0         2
2            960             0         2
4            900             5         3
6            480             0         1
7           1200             5         4
9           1080             0         2
10           660             0         1
12          1620            10         3
15          1980             5         3
17          1800            10         6

In [112]:
production['Variable Cost per Unit'] = (
    production['Cost of Production (per unit)']
    + production['Wages (per unit)']
)
production.head()

,S.No,Date,Category,Total Products,Defective Products,Cost of Production (per unit),Wages (per unit),Raw Material Batch ID,Artisan Name/ID,Month,Variable Cost per Unit
0,1,2025-10-01,Cotton Scarf,15,1,85,40,RM-A-101,A01,October,125
1,2,2025-10-02,T-Shirt,10,0,180,60,RM-A-101,A02,October,240
2,3,2025-10-03,Chanderi Dupatta,8,0,210,55,RM-A-102,A03,October,265
3,4,2025-10-04,Chanderi Scarf,12,0,150,50,RM-A-102,A04,October,200
4,5,2025-10-05,cotton scarf,15,0,87,40,RM-B-103,A01,October,127

In [115]:
production_cost = production.groupby(
    ['Month', 'Category']
).agg(
    Avg_Production_Cost=(
        'Cost of Production (per unit)', 'mean'
    ),
    Avg_Wages=(
        'Wages (per unit)', 'mean'
    )
).reset_index()
production_cost

       Month          Category  Avg_Production_Cost  Avg_Wages
0   November  Chanderi Dupatta           210.857143       55.0
1   November    Chanderi Scarf           150.400000       50.0
2   November      Cotton Scarf            86.000000       40.0
3   November           T-Shirt           182.000000       60.0
4   November  chanderi Dupatta           212.000000       55.0
5   November    chanderi scarf           150.500000       50.0
6   November      cotton scarf            86.000000       40.0
7    October  Chanderi Dupatta           212.500000       55.0
8    October    Chanderi Scarf           151.200000       50.0
9    October      Cotton Scarf            85.400000       40.0
10   October           T-Shirt           182.142857       60.0
11   October    chanderi scarf           150.000000       50.0
12   October      cotton scarf            87.000000       40.0

combined sales

In [119]:
sales_summary = pd.concat(
    [retail_summary, stall_summary],
    ignore_index=True
)
sales_summary ## returned units have nan values because the the stall sales have no retrun

,Month,Category,Units_Sold,Returned_Units,Gross_Revenue,Net_Revenue
0,November,Chanderi Dupatta,3.0,0.0,1650.0,1650.0
1,November,Chanderi Scarf,4.0,0.0,1600.0,1600.0
2,November,Cotton Scarf,11.0,0.0,2750.0,2750.0
3,November,T-Shirt,2.0,3.0,2250.0,900.0
4,October,Chanderi Dupatta,2.0,0.0,1100.0,1100.0
5,October,Chanderi Scarf,2.0,0.0,800.0,800.0
6,October,Cotton Scarf,6.0,0.0,1500.0,1500.0
7,October,T-Shirt,4.0,1.0,2250.0,1800.0
8,November,Chanderi Dupatta,6.0,NaN,3960.0,3861.0
9,November,Chanderi Scarf,1.0,NaN,480.0,480.0
10,November,Cotton Scarf,9.0,NaN,2700.0,2520.0
11,November,T-Shirt,3.0,NaN,1620.0,1458.0
12,October,Chanderi Dupatta,1.0,NaN,660.0,660.0
13,October,Chanderi Scarf,3.0,NaN,1440.0,1440.0
14,October,Cotton Scarf,9.0,NaN,2700.0,2595.0
15,October,T-Shirt,2.0,NaN,1080.0,1080.0

In [120]:
total_sales = sales_summary.groupby(
    ['Month', 'Category']
).agg(
    Units_Sold=('Units_Sold', 'sum'),
    Net_Revenue=('Net_Revenue', 'sum')
).reset_index()
total_sales

      Month          Category  Units_Sold  Net_Revenue
0  November  Chanderi Dupatta         9.0       5511.0
1  November    Chanderi Scarf         5.0       2080.0
2  November      Cotton Scarf        20.0       5270.0
3  November           T-Shirt         5.0       2358.0
4   October  Chanderi Dupatta         3.0       1760.0
5   October    Chanderi Scarf         5.0       2240.0
6   October      Cotton Scarf        15.0       4095.0
7   October           T-Shirt         6.0       2880.0

In [121]:
final = total_sales.merge(
    production_cost,
    on=['Month', 'Category'],
    how='left'
)
final

,Month,Category,Units_Sold,Net_Revenue,Avg_Production_Cost,Avg_Wages
0,November,Chanderi Dupatta,9.0,5511.0,210.857143,55.0
1,November,Chanderi Scarf,5.0,2080.0,150.400000,50.0
2,November,Cotton Scarf,20.0,5270.0,86.000000,40.0
3,November,T-Shirt,5.0,2358.0,182.000000,60.0
4,October,Chanderi Dupatta,3.0,1760.0,212.500000,55.0
5,October,Chanderi Scarf,5.0,2240.0,151.200000,50.0
6,October,Cotton Scarf,15.0,4095.0,85.400000,40.0
7,October,T-Shirt,6.0,2880.0,182.142857,60.0

operational summary

In [125]:
operations['Date'] = pd.to_datetime(
    operations['Date'],
    dayfirst=True
)
operations['Month'] = operations['Date'].dt.month_name()
monthly_operations = operations.groupby(
    'Month'
).agg(
    Total_Operating_Expense=('Amount', 'sum')
).reset_index()
monthly_operations

      Month  Total_Operating_Expense
0  November                     5100
1   October                     2850

In [128]:
total_sales

      Month          Category  Units_Sold  Net_Revenue
0  November  Chanderi Dupatta         9.0       5511.0
1  November    Chanderi Scarf         5.0       2080.0
2  November      Cotton Scarf        20.0       5270.0
3  November           T-Shirt         5.0       2358.0
4   October  Chanderi Dupatta         3.0       1760.0
5   October    Chanderi Scarf         5.0       2240.0
6   October      Cotton Scarf        15.0       4095.0
7   October           T-Shirt         6.0       2880.0

In [132]:
# Merge sales summary with production cost
financial_data = total_sales.merge(
    production_cost,
    on=['Month', 'Category'],
    how='left'
)

# Calculate COGS
financial_data['COGS'] = (
    financial_data['Units_Sold']
    * financial_data['Avg_Production_Cost']
)

# Calculate Gross Profit
financial_data['Gross_Profit'] = (
    financial_data['Net_Revenue']
    - financial_data['COGS']
)

# Merge monthly operating expenses
financial_data = financial_data.merge(
    monthly_operations,
    on='Month',
    how='left'
)

# Monthly financial summary
monthly_financial = financial_data.groupby(
    'Month'
).agg(
    Total_Revenue=('Net_Revenue', 'sum'),
    COGS=('COGS', 'sum'),
    Gross_Profit=('Gross_Profit', 'sum'),
    Total_Operating_Expense=('Total_Operating_Expense', 'first')
).reset_index()

# Calculate Net Profit
monthly_financial['Net_Profit'] = (
    monthly_financial['Gross_Profit']
    - monthly_financial['Total_Operating_Expense']
)

# Display final result
monthly_financial

,Month,Total_Revenue,COGS,Gross_Profit,Total_Operating_Expense,Net_Profit
0,November,15219.0,5279.714286,9939.285714,5100,4839.285714
1,October,10975.0,3767.357143,7207.642857,2850,4357.642857

profit margin

In [141]:
operations.columns
operations.columns = operations.columns.str.strip()
operations.columns
print([repr(col) for col in operations.columns])

["'Expense ID'", "'Date'", "'Expense Category'", "'Expenese Channel'", "'Description'", "'Amount'", "'Month'"]